;Double operand test
START:
MOV #7763, R0
MOV R0, R1	;R1 = 7763
CMP R0, R1	;Z flag should be set
MOV #7, R2	;R2 = 7
BIC R2, R1	;R1 = 4080
CMP R1, R0	;Z flag should not be set, N flag set
MOV #14, R2	;R2 = 14
BIS R2, R1	;R1 = 7774
SUB R0, R1	;(R1 - R0 = R1), R1 = 11
ADD #12163, R0 ;R0 = 22146
SUB R0, R1	;11 - 22146 = -155643, N should be set and R1 = 155643
MOV #9308, R0	;22134 and 155643 share no bits in common
BIT R0, R1	;Z should be set, N should be cleared
MOV #176167, R2	;N should be set
BIT R2, R1	;Z should not be set, N should be set
MOV #4, R4	;Z should not be set
MOV #0, R4	;Z should be set
ADD #1611, R2	;Z should be set, N not set
ADD #0, R4	;Z should be set
.END START