;Single operand test
START:
MOV #20, R0
CLR R0	;R0 = 0, Z gets set, all other flags cleared
MOV #-2, R0	;R0 = -2
INC R0	;R0 = -1, N gets set, all
INC R0	;R0 = 0, Z gets set
MOV #77777, R0
INC R0	;V flag should be set
MOV #2, R0
DEC R0	;R0 = 1
DEC R0	;R0 = 0, Z flag set
DEC R0	;R0 = -1, N flag set
MOV #100000, R0
DEC R0	;C should be set? (says C in manual, but seems like it should be V flag)
MOV #1023, R0	;R0 = 1023
NEG R0	;R0 = 176754 N set
NEG R0	;R0 = 1023, N cleared
MOV #100000, R0	;R0 = 100000
NEG R0	;R0 = 100000, V flag should be set
TST R0	;C and V cleared, N set
MOV #0, R0
TST R0	;N cleared, Z set
MOV #177236, R0
COM R0	;R0 = 541, N cleared, V cleared, C set
COM R0	;R0 = 177236, N set, V cleared, C set
ADC R0	;R0 = 177237,
;Multiple precision operations
MOV #13607, R0
MOV #77776, R1
MOV #2, R2
ADD R0, R1	;C is set
ADC R2	;R2 = 3
MOV #77776, R1
ADD R0, R1	;C is set
SBC R2	;R2 = 2
MOV #1, R1
ROR R1	;R1 = 0, C is set, Z is set, N is cleared, V is set
ROR R1	;R1 = 100000, C is cleared, N is set, V is set
MOV #1, R1
ROR R1	;C is set
ROL R2	;R2 = 5, C cleared
MOV #3, R0
SWAB R0	;R0 = 1400, Z set
MOV #1700, R0
SWAB R0	;R0 = 140 003, all flags cleared
SWAB R0 ;R0 = 1700, N set
MOV #177772, R0
ASR R0	;R0 = 177775, N set, C cleared, V set
ASR R0	;R0 = 177777, C set, N set, V cleared
ASR R0	;R0 = 0, Z flag set, C flag set, N cleared, V set
MOV #177772, R0
ASL R0	;R0 = 177764, N is set, C is set, V cleared
MOV #177777, R0
ASL R0	;R0 = 0, Z is set, N is cleared, C set, V set
.END START